### PR TITLE
Renewed the layout class + extra changes

### PR DESCRIPTION
**Pull request by ghost**
It's renewed so it is easier to edit the layouts. Also I tried to
refactor some other code and add an information class.

Please don't commit it. It's just so we can discuss if this is the right way to go. I need to cleanup a little to make it a good pull request

### CODE REVIEW

**Comment by ghost** [comment]
It is now completly polished and updated

**Comment by ghost** [comment]
Hey Napalm, I'm trying to register for the OpenRPS forum but I'm still waiting to be approved. Thought I'd contact you on here. My username might be this one or WhiskeyJack on there I can't remember.

**Comment by ghost** [comment]
I don't have administrator rights on the forums. I hope spiraltarget sees it soon he administers the forums.

**Comment by ghost** [comment]
Actually I was hoping to talk to you about using GitHub. I'd like to contribute to what you guys are working on, and I'm working on another resource monitoring project with another guy that will also require a VCS.

My email is jackothe1st@gmail.com if you want drop me an email and we can discuss from there. I couldn't find you email address on here.

**Comment by irontet** [comment]
I can add you into github I will tonight.
Thanks,

-Ben

On Tue, Jun 30, 2015 at 10:23 AM, napalm-a notifications@github.com wrote:
I don't have administrator rights on the forums. I hope spiraltarget sees it
soon he administers the forums.

—
Reply to this email directly or view it on GitHub
[https://github.com/bmilliron/OpenRPSDev/pull/1#issuecomment-117205431] .[https://github.com/notifications/beacon/AJkWn0UzhTVyE03n2UOx4Sih3i2TGFyNks5oYp3PgaJpZM4FMujL.gif]

**Comment by irontet** [comment]
JackoThe1st I sent you an email, reply and I will add you to the Open RPS forums. I added you and napalm as GitHub collaborators for the project.

**Comment by irontet** [comment]
I posted on the OpenRPS forums, I'd like to get a dedicated PHP person involved. You can read the forum post. Thanks. http://openrps.org/index.php?topic=76.0

**Comment by irontet** [comment]
I added a milestone.

**Comment by ghost** [comment]
I now added javascript validation and some basic work on promotional.

**Comment by irontet** [comment]
I am merging this pull request

**Pull request merged**
